export type TagCategory =
  | "emotion"
  | "pause"
  | "gesture"
  | "director"
  | "ssml"
  | "custom";

export interface TagItem {
  id: string;
  name: string;
  syntax: string;
  category: TagCategory;
  description: string;
  engines: ("gemini" | "orpheus" | "kokoro" | "chatterbox" | "piper" | "qwen3")[];
  badgeColor?: string;
  exampleSnippet: string;
  isCustom?: boolean;
}

export const TAG_CATEGORIES: { id: TagCategory; label: string; icon: string; countHint?: number }[] = [
  { id: "emotion", label: "Emotions & Inflections", icon: "🎭" },
  { id: "pause", label: "Pacing & Pauses", icon: "⏱️" },
  { id: "gesture", label: "Audio Gestures & Sounds", icon: "✨" },
  { id: "director", label: "Director Styles & Accents", icon: "🎬" },
  { id: "ssml", label: "SSML & Audio Markup", icon: "⚡" },
  { id: "custom", label: "Custom Studio Tags", icon: "🌟" },
];

export const BUILTIN_TAGS: TagItem[] = [
  // --- EMOTIONS & INFLECTIONS ---
  {
    id: "tag-warm",
    name: "Warm",
    syntax: "[warm]",
    category: "emotion",
    description: "Friendly, comforting, and approachable tone for storytelling and greetings.",
    engines: ["gemini", "orpheus"],
    badgeColor: "amber",
    exampleSnippet: "[warm] Welcome home. It is so wonderful to see you again.",
  },
  {
    id: "tag-warm-celebratory",
    name: "Warm & Celebratory",
    syntax: "[warm, celebratory]",
    category: "emotion",
    description: "Joyful, uplifting, and festive delivery for announcements and achievements.",
    engines: ["gemini"],
    badgeColor: "amber",
    exampleSnippet: "[warm, celebratory] Congratulations on reaching this incredible milestone!",
  },
  {
    id: "tag-excited",
    name: "Excited & Energetic",
    syntax: "[excited]",
    category: "emotion",
    description: "Upbeat, energetic, and eager delivery with higher dynamic pitch.",
    engines: ["gemini", "orpheus"],
    badgeColor: "orange",
    exampleSnippet: "[excited] We just launched the fastest speech engine ever built!",
  },
  {
    id: "tag-reflective",
    name: "Reflective & Contemplative",
    syntax: "[reflective]",
    category: "emotion",
    description: "Deep, thoughtful, literary cadence ideal for memoirs and audiobooks.",
    engines: ["gemini"],
    badgeColor: "indigo",
    exampleSnippet: "[reflective] Looking back, those quiet winter mornings shaped who we became.",
  },
  {
    id: "tag-intense-deep",
    name: "Intense & Deep",
    syntax: "[intense, deep]",
    category: "emotion",
    description: "Authoritative low-end resonance and suspenseful dramatic gravitas.",
    engines: ["gemini"],
    badgeColor: "purple",
    exampleSnippet: "[intense, deep] In a world where silence was outlawed... one sound remained.",
  },
  {
    id: "tag-soft-gentle",
    name: "Soft & Gentle",
    syntax: "[soft, gentle]",
    category: "emotion",
    description: "Tender, soothing delivery designed for meditations, lullabies, and ASMR.",
    engines: ["gemini"],
    badgeColor: "teal",
    exampleSnippet: "[soft, gentle] Close your eyes and allow your breath to settle naturally.",
  },
  {
    id: "tag-calm-peaceful",
    name: "Calm & Peaceful",
    syntax: "[warm, calming]",
    category: "emotion",
    description: "Relaxed, centered cadence for therapeutic guidance and tutorials.",
    engines: ["gemini"],
    badgeColor: "emerald",
    exampleSnippet: "[warm, calming] Feel the stillness around you in this quiet moment.",
  },
  {
    id: "tag-authoritative",
    name: "Authoritative & Poised",
    syntax: "[authoritative]",
    category: "emotion",
    description: "Commanding, credible, executive broadcast standard.",
    engines: ["gemini"],
    badgeColor: "blue",
    exampleSnippet: "[authoritative] The board has officially ratified the strategic roadmap for 2027.",
  },
  {
    id: "tag-formal-clear",
    name: "Formal & Clear",
    syntax: "[formal, clear]",
    category: "emotion",
    description: "Crisp, articulated news anchor diction without emotional bias.",
    engines: ["gemini"],
    badgeColor: "sky",
    exampleSnippet: "[formal, clear] Good evening. Our top story tonight: localized AI models break records.",
  },
  {
    id: "tag-whispering",
    name: "Whispering",
    syntax: "[whispering]",
    category: "emotion",
    description: "Intimate near-mic whisper with high frequency air and close proximity.",
    engines: ["gemini", "orpheus"],
    badgeColor: "cyan",
    exampleSnippet: "[whispering] Listen closely. Do not make a single sound.",
  },
  {
    id: "tag-playful",
    name: "Playful & Animated",
    syntax: "[playful]",
    category: "emotion",
    description: "Whimsical, colorful inflection for children's stories and cartoon voices.",
    engines: ["gemini", "orpheus"],
    badgeColor: "pink",
    exampleSnippet: "[playful] Guess who just sneaked into the enchanted kitchen?",
  },
  {
    id: "tag-sympathetic",
    name: "Empathetic & Caring",
    syntax: "[sympathetic]",
    category: "emotion",
    description: "Compassionate, heartfelt delivery acknowledging difficulty.",
    engines: ["gemini"],
    badgeColor: "rose",
    exampleSnippet: "[sympathetic] I understand how difficult this journey has been for you.",
  },
  {
    id: "tag-dramatic",
    name: "Dramatic & Cinematic",
    syntax: "[dramatic]",
    category: "emotion",
    description: "Heightened tension, theatrical timing, and expressive cadence.",
    engines: ["gemini"],
    badgeColor: "violet",
    exampleSnippet: "[dramatic] The ancient gates slowly creaked open for the first time in centuries.",
  },
  {
    id: "tag-urgent",
    name: "Urgent & Alert",
    syntax: "[urgent]",
    category: "emotion",
    description: "Fast-paced, high-stakes delivery demanding immediate attention.",
    engines: ["gemini"],
    badgeColor: "red",
    exampleSnippet: "[urgent] All personnel must evacuate sector 4 immediately.",
  },
  {
    id: "tag-melancholic",
    name: "Melancholic & Somber",
    syntax: "[melancholic]",
    category: "emotion",
    description: "Sad, wistful, resonant delivery for emotional climaxes.",
    engines: ["gemini"],
    badgeColor: "slate",
    exampleSnippet: "[melancholic] The last autumn leaves fell upon the silent river.",
  },
  {
    id: "tag-triumphant",
    name: "Triumphant & Victorious",
    syntax: "[triumphant]",
    category: "emotion",
    description: "Inspiring, powerful climax celebrating achievement.",
    engines: ["gemini"],
    badgeColor: "yellow",
    exampleSnippet: "[triumphant] Against all odds, the summit was conquered at last!",
  },
  {
    id: "tag-sarcastic",
    name: "Sarcastic & Dry",
    syntax: "[sarcastic]",
    category: "emotion",
    description: "Wry, sardonic inflection with ironic undertones.",
    engines: ["gemini"],
    badgeColor: "orange",
    exampleSnippet: "[sarcastic] Oh wonderful, another software update right before my deadline.",
  },
  {
    id: "tag-mysterious",
    name: "Mysterious & Cryptic",
    syntax: "[mysterious]",
    category: "emotion",
    description: "Hushed, intriguing cadence for puzzles and thriller narratives.",
    engines: ["gemini"],
    badgeColor: "purple",
    exampleSnippet: "[mysterious] Behind the locked door lay the one secret they tried to bury.",
  },

  // --- PACING & PAUSES ---
  {
    id: "tag-pause-05",
    name: "Micro Pause (0.5s)",
    syntax: "[pause: 0.5s]",
    category: "pause",
    description: "Short rhythmic breath between comma clauses or bullet points.",
    engines: ["gemini", "orpheus", "kokoro", "chatterbox", "piper", "qwen3"],
    badgeColor: "cyan",
    exampleSnippet: "First we optimize the audio [pause: 0.5s] then we export to 48kHz.",
  },
  {
    id: "tag-pause-08",
    name: "Short Pause (0.8s)",
    syntax: "[pause: 0.8s]",
    category: "pause",
    description: "Natural conversational pause between related sentences.",
    engines: ["gemini", "orpheus", "kokoro", "chatterbox", "piper", "qwen3"],
    badgeColor: "cyan",
    exampleSnippet: "Welcome back to the podcast. [pause: 0.8s] Today we have a special guest.",
  },
  {
    id: "tag-pause-10",
    name: "Standard Sentence Pause (1.0s)",
    syntax: "[pause: 1.0s]",
    category: "pause",
    description: "Standard broadcast period pause giving listeners time to digest.",
    engines: ["gemini", "orpheus", "kokoro", "chatterbox", "piper", "qwen3"],
    badgeColor: "cyan",
    exampleSnippet: "This marks a major breakthrough in speech synthesis. [pause: 1.0s] Let's look at the data.",
  },
  {
    id: "tag-pause-15",
    name: "Paragraph & Dramatic Pause (1.5s)",
    syntax: "[pause: 1.5s]",
    category: "pause",
    description: "Substantial pause between sections or for dramatic anticipation.",
    engines: ["gemini", "orpheus", "kokoro", "chatterbox", "piper", "qwen3"],
    badgeColor: "cyan",
    exampleSnippet: "And the winner of this year's sound design award is... [pause: 1.5s] KobeanAudio!",
  },
  {
    id: "tag-pause-20",
    name: "Scene Transition Pause (2.0s)",
    syntax: "[pause: 2.0s]",
    category: "pause",
    description: "Long transition pause between chapters, scenes, or movements.",
    engines: ["gemini", "orpheus", "kokoro", "chatterbox", "piper", "qwen3"],
    badgeColor: "indigo",
    exampleSnippet: "Chapter One: The Whispering Forest. [pause: 2.0s] The morning sun broke through the trees.",
  },
  {
    id: "tag-pause-30",
    name: "Meditation Breathing Pause (3.0s)",
    syntax: "[pause: 3.0s]",
    category: "pause",
    description: "Extended mindfulness space for breathing exercises and silence.",
    engines: ["gemini", "orpheus", "kokoro", "chatterbox", "piper", "qwen3"],
    badgeColor: "teal",
    exampleSnippet: "Breathe in deeply through your nose... [pause: 3.0s] and exhale slowly.",
  },
  {
    id: "tag-brief-pause",
    name: "Brief Natural Pause",
    syntax: "[brief pause]",
    category: "pause",
    description: "Organic speech cadence hesitation without rigid second measurement.",
    engines: ["gemini"],
    badgeColor: "sky",
    exampleSnippet: "I think that... [brief pause] we have discovered something extraordinary.",
  },
  {
    id: "tag-dramatic-pause",
    name: "Dramatic Suspension",
    syntax: "[dramatic pause]",
    category: "pause",
    description: "Suspenseful hold building listener anticipation before a reveal.",
    engines: ["gemini"],
    badgeColor: "purple",
    exampleSnippet: "He opened the old wooden chest... [dramatic pause] and it was completely empty.",
  },

  // --- AUDIO GESTURES & SOUNDS ---
  {
    id: "tag-laugh",
    name: "Laugh",
    syntax: "<laugh>",
    category: "gesture",
    description: "Natural vocal laugh or chuckle mid-sentence.",
    engines: ["gemini", "orpheus"],
    badgeColor: "amber",
    exampleSnippet: "<laugh> You cannot be serious! That actually worked?",
  },
  {
    id: "tag-sigh",
    name: "Sigh",
    syntax: "<sigh>",
    category: "gesture",
    description: "Audible breath of relief, weariness, or wistfulness.",
    engines: ["gemini", "orpheus"],
    badgeColor: "slate",
    exampleSnippet: "<sigh> It has been a very long day, but we made it.",
  },
  {
    id: "tag-gasp",
    name: "Gasp",
    syntax: "<gasp>",
    category: "gesture",
    description: "Sudden sharp intake of breath indicating shock or surprise.",
    engines: ["gemini", "orpheus"],
    badgeColor: "rose",
    exampleSnippet: "<gasp> Look at the northern lights dancing across the sky!",
  },
  {
    id: "tag-chuckle",
    name: "Chuckle",
    syntax: "<chuckle>",
    category: "gesture",
    description: "Subtle, amused low laughter between words.",
    engines: ["gemini", "orpheus"],
    badgeColor: "yellow",
    exampleSnippet: "<chuckle> That reminds me of our first studio recording in 2020.",
  },
  {
    id: "tag-giggle",
    name: "Giggle",
    syntax: "<giggle>",
    category: "gesture",
    description: "Lighthearted, youthful chuckle.",
    engines: ["gemini", "orpheus"],
    badgeColor: "pink",
    exampleSnippet: "<giggle> The puppy tried to wear the headphones!",
  },
  {
    id: "tag-clears-throat",
    name: "Clears Throat",
    syntax: "[clears throat]",
    category: "gesture",
    description: "Formal or awkward vocal throat clear before speaking.",
    engines: ["gemini"],
    badgeColor: "zinc",
    exampleSnippet: "[clears throat] Ahem. As I was saying regarding the quarterly report...",
  },
  {
    id: "tag-snicker",
    name: "Snicker",
    syntax: "[snicker]",
    category: "gesture",
    description: "Suppressed mischievous laugh.",
    engines: ["gemini"],
    badgeColor: "orange",
    exampleSnippet: "[snicker] Wait until you see what he wrote on the whiteboard.",
  },

  // --- DIRECTOR STYLES & ACCENTS ---
  {
    id: "tag-reading",
    name: "Reading / Literary Narration",
    syntax: "[reading]",
    category: "director",
    description: "Polished audiobook cadence delivering written text faithfully.",
    engines: ["gemini"],
    badgeColor: "indigo",
    exampleSnippet: "[reading] Chapter Four: The Architecture of Neural Sound.",
  },
  {
    id: "tag-title",
    name: "Title Announcement",
    syntax: "[title]",
    category: "director",
    description: "Bold introductory heading inflection with resonant clarity.",
    engines: ["gemini"],
    badgeColor: "blue",
    exampleSnippet: "[title] KobeanAudio: The Neural Workstation.",
  },
  {
    id: "tag-emphasis",
    name: "Strong Emphasis",
    syntax: "[emphasis]",
    category: "director",
    description: "Accentuates the following key words with higher vocal stress.",
    engines: ["gemini"],
    badgeColor: "violet",
    exampleSnippet: "This is [emphasis] not a simulation, it is running natively on Metal.",
  },
  {
    id: "tag-accent-british-rp",
    name: "British RP Accent",
    syntax: "[accent: British RP]",
    category: "director",
    description: "Refined Received Pronunciation BBC / classical theater diction.",
    engines: ["gemini"],
    badgeColor: "red",
    exampleSnippet: "[accent: British RP] Good afternoon, ladies and gentlemen.",
  },
  {
    id: "tag-accent-american-southern",
    name: "American Southern",
    syntax: "[accent: American Southern]",
    category: "director",
    description: "Warm, drawled Southern cadence with melodic pacing.",
    engines: ["gemini"],
    badgeColor: "amber",
    exampleSnippet: "[accent: American Southern] Well now, that sure makes a whole lot of sense.",
  },
  {
    id: "tag-accent-transatlantic",
    name: "Transatlantic / Vintage Radio",
    syntax: "[accent: Transatlantic]",
    category: "director",
    description: "Golden-age Hollywood and classic mid-century broadcast voice.",
    engines: ["gemini"],
    badgeColor: "yellow",
    exampleSnippet: "[accent: Transatlantic] Broadcasting live across the continental airwaves.",
  },
  {
    id: "tag-fast-tempo",
    name: "Fast Tempo / High Energy",
    syntax: "[fast tempo]",
    category: "director",
    description: "Rapid, punchy delivery for product spots and disclaimers.",
    engines: ["gemini"],
    badgeColor: "orange",
    exampleSnippet: "[fast tempo] Available today on macOS, iOS, and Web. Terms and conditions apply.",
  },
  {
    id: "tag-slow-cadence",
    name: "Slow & Measured Cadence",
    syntax: "[slow cadence]",
    category: "director",
    description: "Unhurried, deliberate speech for poetry, philosophy, and instruction.",
    engines: ["gemini"],
    badgeColor: "teal",
    exampleSnippet: "[slow cadence] Time, like sound, ripples endlessly into eternity.",
  },

  // --- SSML & AUDIO MARKUP ---
  {
    id: "tag-ssml-break-1s",
    name: "SSML Break (1.0s)",
    syntax: '<break time="1s"/>',
    category: "ssml",
    description: "Standard W3C SSML silence tag for cross-platform neural engines.",
    engines: ["kokoro", "piper", "qwen3"],
    badgeColor: "emerald",
    exampleSnippet: 'Section one complete. <break time="1s"/> Beginning section two.',
  },
  {
    id: "tag-ssml-emphasis",
    name: "SSML Emphasis Strong",
    syntax: '<emphasis level="strong">',
    category: "ssml",
    description: "W3C SSML pitch & volume boost on targeted phrase.",
    engines: ["piper", "kokoro"],
    badgeColor: "blue",
    exampleSnippet: '<emphasis level="strong">Crucial requirement:</emphasis> Always normalize LUFS.',
  },
  {
    id: "tag-ssml-prosody-slow",
    name: "SSML Prosody Slow Rate",
    syntax: '<prosody rate="slow">',
    category: "ssml",
    description: "W3C SSML playback rate deceleration.",
    engines: ["piper"],
    badgeColor: "purple",
    exampleSnippet: '<prosody rate="slow">Listen with extreme care.</prosody>',
  },
];
